// export const ADD_SERVICE = 'ADD_SERVICE';
// export const REMOVE_SERVICE = 'REMOVE_SERVICE';
// export const EDIT_SERVICE = 'EDIT_SERVICE';
// export const GET_SERVICE = 'GET_SERVICE';

// export const CHANGE_ADD_SERVICE_FIELD = 'CHANGE_ADD_SERVICE_FIELD';
// export const RESET_EDIT_FORM = 'RESET_EDIT_FORM';

// export const CHANGE_EDIT_SERVICE_FIELD = 'CHANGE_EDIT_SERVICE_FIELD';
// export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';
// export const FILL_EDIT_FORM = 'FILL_EDIT_FORM';

// export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
// export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
// export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

// export const ADD_SERVICE_REQUEST = 'ADD_SERVICE_REQUEST';
// export const ADD_SERVICE_FAILURE = 'ADD_SERVICE_FAILURE';
// export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';

// export const EDIT_SERVICE_REQUEST = 'EDIT_SERVICE_REQUEST';
// export const EDIT_SERVICE_FAILURE = 'EDIT_SERVICE_FAILURE';
// export const EDIT_SERVICE_SUCCESS = 'EDIT_SERVICE_SUCCESS';
